--create CR testcases.
--
--@author dhruv
--@since 2023-09-13

INSERT INTO
    specification (
        id,
        name,
        description,
        state,
        rank,
        is_functional,
        component_id,
        created_by,
        updated_by,
        created_at,
        updated_at,
        version
    )
VALUES
    (
        'specification.cr.crf.2',
        'CRF-2',
        'CRF-2 Specification of the Client Repository Component (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/client-registry)',
        'specification.status.active',
        5,
        true,
        'component.client.repository',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    );

INSERT INTO
    testcase (
        id,
        name,
        description,
        state,
        rank,
        is_manual,
        is_required,
        bean_name,
        specification_id,
        created_by,
        updated_by,
        created_at,
        updated_at,
        version
    )
VALUES
    (
        'testcase.cr.crf.2.1',
        'As a user, does the system implement accurate and efficient methods for patient linking and de-duplication? For example, can you reference a specific instance where the system successfully linked and de-duplicated patient records accurately?',
        'Question for the CRF-2 Specification of the Client Repository',
        'testcase.status.active',
        1,
        true,
        true,
        null,
        'specification.cr.crf.2',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.2',
        'Can you, as a user, easily view merge/linkage operations in the system in a way that is both intuitive and user-friendly? For instance, have you been able to navigate the system to monitor merge/linkage operations effortlessly?',
        'Question for the CRF-2 Specification of the Client Repository',
        'testcase.status.active',
        2,
        true,
        true,
        null,
        'specification.cr.crf.2',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.3',
        'In the system, is there a feature that allows you to manually accept or reject merge suggestions in a straightforward and intuitive manner? Additionally, can you choose fields from either record to be merged? Have you had a scenario where you needed to manually intervene in the merging process?',
        'Question for the CRF-2 Specification of the Client Repository',
        'testcase.status.active',
        2,
        true,
        true,
        null,
        'specification.cr.crf.2',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    );

INSERT INTO
    testcase_option (
        id,
        name,
        description,
        state,
        rank,
        is_success,
        testcase_id,
        created_by,
        updated_by,
        created_at,
        updated_at,
        version
    )
VALUES
    (
        'testcase.cr.crf.2.1.option.1',
        'YES',
        'YES',
        'testcase.option.status.active',
        1,
        true,
        'testcase.cr.crf.2.1',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.1.option.2',
        'NO',
        'NO',
        'testcase.option.status.active',
        2,
        false,
        'testcase.cr.crf.2.1',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.2.option.1',
        'YES',
        'YES',
        'testcase.option.status.active',
        1,
        true,
        'testcase.cr.crf.2.2',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.2.option.2',
        'NO',
        'NO',
        'testcase.option.status.active',
        2,
        false,
        'testcase.cr.crf.2.2',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.3.option.1',
        'YES',
        'YES',
        'testcase.option.status.active',
        1,
        true,
        'testcase.cr.crf.2.3',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    ),
    (
        'testcase.cr.crf.2.3.option.2',
        'NO',
        'NO',
        'testcase.option.status.active',
        2,
        false,
        'testcase.cr.crf.2.3',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0
    );