--create FR automated testcases audit.
--
--@author dhruv
--@since 2023-09-13
INSERT INTO component_aud (id,
                           name,
                           description,
                           state,
                           rank,
                           created_by,
                           updated_by,
                           created_at,
                           updated_at,
                           version,
                           rev,
                           revtype)
VALUES ('component.facility.registry',
        'Facility Registry (FR)',
        'Facility Registry Component (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/openhie-facility-registry-fr)',
        'component.status.active',
        2,
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0);

INSERT INTO specification_aud (id,
                               name,
                               description,
                               state,
                               rank,
                               is_functional,
                               is_required,
                               component_id,
                               created_by,
                               updated_by,
                               created_at,
                               updated_at,
                               version,
                               rev,
                               revtype)
VALUES ('specification.fr.frwf.1',
        'FRWF-1',
        'FRWF-1 Specification of the Facility Registry (https://guides.ohie.org/arch-spec/introduction/care-services-discovery/query-health-worker-and-or-facility-records-workflow)',
        'specification.status.active',
        1,
        false,
        true,
        'component.facility.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('specification.fr.frf.9',
        'FRF-9',
        'FRF-9 Specification of the Facility Registry (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/openhie-facility-registry-fr)',
        'specification.status.active',
        10,
        true,
        false,
        'component.facility.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0);

INSERT INTO testcase_aud (id,
                          name,
                          description,
                          state,
                          rank,
                          is_manual,
                          test_suite_id,
                          specification_id,
                          created_by,
                          updated_by,
                          created_at,
                          updated_at,
                          version,
                          rev,
                          revtype,
                          test_case_run_environment,
                          sut_actor_api_key)
VALUES ('testcase.fr.frwf.1.1',
        'Verify Create Organization and Location',
        'Testcase to verify create Organization and Location for specification FRWF1 of the fr repository',
        'testcase.status.active',
        1,
        false,
        'testcase.fr.frwf.1.1~Verify Create Organization and Location~0',
        'specification.fr.frwf.1',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0,
        'testcase.run.environment.eu.testbed','D6A58024X3EFDX4B2DX8C81X461719B08B66'),
       ('testcase.fr.frf.9.1',
        'Search facilities by attribute',
        'Test case to verify the ability to  search for facilities by attribute.',
        'testcase.status.active',
        1,
        false,
        'testcase.fr.frf.9.1~Search facilities by attribute~0',
        'specification.fr.frf.9',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0,
        'testcase.run.environment.eu.testbed','D6A58024X3EFDX4B2DX8C81X461719B08B66');


