--create HWR automated testcases audit.
--
--@author dhruv
--@since 2023-09-13
INSERT INTO component_aud (id,
                           name,
                           description,
                           state,
                           rank,
                           created_by,
                           updated_by,
                           created_at,
                           updated_at,
                           version,
                           rev,
                           revtype)
VALUES ('component.health.worker.registry',
        'Health Worker Registry (HWR)',
        'Health Worker Registry Component (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/openhie-health-worker-registry-hwr)',
        'component.status.active',
        5,
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0);

INSERT INTO specification_aud (id,
                               name,
                               description,
                               state,
                               rank,
                               is_functional,
                               is_required,
                               component_id,
                               created_by,
                               updated_by,
                               created_at,
                               updated_at,
                               version,
                               rev,
                               revtype)
VALUES ('specification.hwr.hwwf.1',
        'HWWF-1',
        'HWWF-1 Specification of the Health Worker Repository Component (https://guides.ohie.org/arch-spec/introduction/care-services-discovery/query-health-worker-and-or-facility-records-workflow)',
        'specification.status.active',
        1,
        false,
        true,
        'component.health.worker.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('specification.hw.hwwf.2',
        'HWWF-2',
        'HWWF-2 Specification of the HealthWorker Registry Component (https://guides.ohie.org/arch-spec/introduction/care-services-discovery/query-care-services-records-workflow)',
        'specification.status.active',
        2,
        false,
        true,
        'component.health.worker.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('specification.hw.hwwf.3',
        'HWWF-3',
        'HWWF-3 Specification of the HealthWorker Registry Component (https://guides.ohie.org/arch-spec/introduction/care-services-discovery/search-care-services-workflow)',
        'specification.status.active',
        3,
        false,
        false,
        'component.health.worker.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('specification.hwr.hwwf.4',
        'HWWF-4',
        'HWWF-4 Specification of the Health Worker Repository Component (https://guides.ohie.org/arch-spec/introduction/care-services-discovery/request-care-services-updates-workflow)',
        'specification.status.active',
        4,
        false,
        true,
        'component.health.worker.registry',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0);

INSERT INTO testcase_aud (id,
                          name,
                          description,
                          state,
                          rank,
                          is_manual,
                          bean_name,
                          specification_id,
                          created_by,
                          updated_by,
                          created_at,
                          updated_at,
                          version,
                          rev,
                          revtype)
VALUES ('testcase.hwr.hwwf.1.1',
        'Verify Create Practitioner',
        'Testcase to verify create practitioner for specification HWWF1 of the healthworker repository',
        'testcase.status.active',
        1,
        false,
        'HWWF1TestCase1',
        'specification.hwr.hwwf.1',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('testcase.hw.hwwf.2.1',
        'Query Care Services Records Workflow ',
        'Testcase to Query Care Services Records Workflow for specification HWWF2 of the HealthWorker Registry',
        'testcase.status.active',
        1,
        false,
        'HWWF2TestCase1',
        'specification.hw.hwwf.2',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('testcase.hw.hwwf.3.1',
        'Search Care Services ',
        'Testcase to search care Service for specification HWWF3 of the HealthWorker Registry',
        'testcase.status.active',
        1,
        false,
        'HWWF3TestCase1',
        'specification.hw.hwwf.3',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0),
       ('testcase.hwr.hwwf.4.1',
        'Verify Care Service Updates',
        'Testcase to verify care service updates for specification HWWF4 of the healthworker registry',
        'testcase.status.active',
        1,
        false,
        'HWWF4TestCase1',
        'specification.hwr.hwwf.4',
        'SYSTEM_USER',
        'SYSTEM_USER',
        Now(),
        Now(),
        0,
        1,
        0);