--create HMIS automated testcases audit.
--
--@author dhruv
--@since 2023-09-13
INSERT INTO component_aud (id,
                           rev,
                           revtype,
                           name,
                           description,
                           state,
                           rank,
                           created_by,
                           updated_by,
                           created_at,
                           updated_at,
                           version)
VALUES ('component.health.management.information.system',
        1,
        0,
        'Health Management Information System (HMIS)',
        'Health Management Information System Component (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/openhie-health-management-information-system-hmis)',
        'component.status.active',
        3,
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0);

INSERT INTO specification_aud (id,
                               rev,
                               revtype,
                               name,
                               description,
                               state,
                               rank,
                               is_functional,
                               is_required,
                               component_id,
                               created_by,
                               updated_by,
                               created_at,
                               updated_at,
                               version)
VALUES ('specification.hmis.hmiswf.1',
        1,
        0,
        'HMISWF-1',
        'HMISWF-1 Specification of the Health Management Information System (https://guides.ohie.org/arch-spec/introduction/aggregate-reporting-workflows/validate-and-save-aggregate-data)',
        'specification.status.inactive',
        1,
        false,
        true,
        'component.health.management.information.system',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0),
       ('specification.hmis.hmisf.1',
        1,
        0,
        'HMISF-1',
        'HMISF-1 Specification of the Health Management Information System (https://guides.ohie.org/arch-spec/openhie-component-specifications-1/openhie-health-management-information-system-hmis)',
        'specification.status.inactive',
        2,
        false,
        false,
        'component.health.management.information.system',
        'ivasiwala@argusoft.com',
        'ivasiwala@argusoft.com',
        Now(),
        Now(),
        0);