base-url: https://tht-testbed.argusservices.in
server:
  port: 8083

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${base-url}/api/login/oauth2/code/google
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_harness_tool_testbed


logging:
  config: classpath:logback-tb.xml

tht-file:
  location: /srv/tht/files-testbed