base-url: https://tht-dev.argusoft.com
server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${base-url}/api/login/oauth2/code/google
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_harness_tool_dev


logging:
  config: classpath:logback-dev.xml

tht-file:
  location: /srv/tht/files-dev