base-url: https://tht-dev.argusoft.com
server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${base-url}/api/login/oauth2/code/google