# ===============================
# ALL PROFILES
# ===============================
base-url: https://tht.argusservices.in
spring:
  cache:
    caches:
      authenticationCache:
        time-to-live: 36000000  #10 hours
    jcache:
      config: classpath:ehcache.xml
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_harness_tool
    username: postgres
    password: argusadmin
  jpa:
    properties:
      org.hibernate.envers.default_revision_entity_name: "CustomRevisionEntity"
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false
      hibernate:
        envers:
          strategy:
            DefaultAuditStrategy
        jdbc:
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_query_cache: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas:
      - public
    table: tht_schema_history
    baseline-version: 0.1
    out-of-order: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 997632152085-pp4ofm9tqfk5149giq4utb54m24et4ig.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
            redirect-uri: ${base-url}/api/login/oauth2/code/google
  servlet:
    multipart:
      max-file-size: 2MB

server:
  servlet:
    context-path: /api
  port: 8081
# ===============================
# LOGGING
# ===============================
logging:
  level:
    org.springframework.http: INFO
    org.springframework.web: INFO
    org.flywaydb.core: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  config: classpath:logback.xml

exception:
  stack-trace:
    enabled: true

tht-file:
  location: /srv/tht/files

captcha:
  false

frontend:
  google.success: /google/success

mailSender:
  username: "noreplytestharnesstool@gmail.com"
  password: "vdspvxnhjnhdklkp"
  host: "smtp.gmail.com"
  port: 587

encryption:
  key: "3a985da74fe225d6c9a29e5a9e4c1b93"

tokenService:
  refresh-token-validity : 2592000 #30 Days
  access-token-validity : 36000 #10 Hours

oauth2:
  tht:
    clientId: "tht"

message-configuration:
  account:
    verify-email:
      mail: true
      notification: false
    forgot-password:
      mail: true
      notification: true
    approve:
      mail: true
      notification: true
    reject:
      mail: true
      notification: true
    deactivate:
      mail: true
      notification: true
    approval-pending:
      mail: true
      notification: true
    reactivate:
      mail: true
      notification: true
  test-request:
    create:
      mail: true
      notification: true
    accept:
      mail: true
      notification: true
    reject:
      mail: true
      notification: true
    finish:
      mail: true
      notification: true